name: Release

on:
  push:
    tags:
      - '**'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
      
      - name: Setup Environment
        uses: ./.github/actions/gradle-setup

      - name: Setup mock google-services.json
        run: |
          cd anylytics-demo
          mv mock-google-services.json google-services.json

      - name: Build demo project
        run: ./gradlew :anylytics-demo:assembleDebug

      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v3

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          token: ${{ secrets.RELEASE_TOKEN }}
          files: ./anylytics-demo/build/outputs/apk/debug/anylytics-demo-debug.apk
